version: '3'
services:
  api:
    container_name: product_service
    build: .
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - postgres
  postgres:
    image: postgres:13.1
    container_name: product_database
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Acaba1234!**
      - APP_DB_USER=admin
      - APP_DB_PASS=Acaba1234!**
      - APP_DB_NAME=hb
    ports:
      - 5435:5432